var fs = require("fs");
var terminalText = process.argv;
//flag:
var valid = "true";

var htmlTitle = "My First Web Page Generated by JavaScript";

//Example of Black List:
if (terminalText[3] == undefined || terminalText[3] == "none") {
    console.log("There was no color specified, so the default white will be used.");

    terminalText[3] = "transparent";
}

//Example of White List:
if (terminalText[3] != "red" || terminalText[3] != "green") {
    console.log("Sorry that is not a proper color value");
    valid = false;
    /*example of a default will be "transparent" expressed as: 
    terminalText[3] = "transparent";   */
}

//if statement relative to flag
if (valid == false){
    return;
}
var ptag = terminalText[4];


var htmlStyle = `
body {
    background-color: ${terminalText[3]};
}`;


var htmlBody = "This homework is complete.";
var htmlFileName = terminalText[2];
var html;



html = `
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>${htmlTitle}</title>
        <meta name="description" content="The HTML5 Herald">
        <meta name="author" content="SitePoint">
        
        <link rel="stylesheet" href="css/styles.css?v=1.0">

        <style>${htmlStyle}</style>
    </head>

    <body>
        ${htmlBody}
        <p>${terminalText[4]}</p>
    </body>
</html>`;


if (htmlFileName == "" || htmlFileName == undefined) {
    console.log("You are missing a file name, cannot continue. !!!!ERROR!!!: ");
    return;
}

var fullFileName = htmlFileName + ".html";

// utf8 is for the file, unlike in the html template meta charset, which is for the browser.
fs.writeFileSync(fullFileName, html, "utf8");

console.log("Generation of HTML file has been completed! Check your folder!");